apiVersion: v1
kind: Pod
metadata:
  name: springapp
spec:
  containers:
  - name: maven
    image: nexus.thanhnc85.lab:8085/maven:3.9.1
    securityContext:
      runAsUser: 1000
    command:
    - sleep
    args:
    - 99d
    envFrom:
      - configMapRef:
          name: sonarqube-configmap
      - secretRef:
          name: sonarqube-secret
    volumeMounts:
      - name: nfs-volume
        mountPath: "/.m2"
  - name: kaniko
    image: nexus.thanhnc85.lab:8085/troynguyeen/kaniko-project-executor:debug
    imagePullPolicy: Always
    securityContext:
      runAsUser: 0
    command:
    - sleep
    args:
    - 99d
    tty: true
    volumeMounts:
      - name: kaniko-volume
        mountPath: /kaniko/.docker
  - name: helm
    image: nexus.thanhnc85.lab:8085/alpine/helm:latest
    securityContext:
      runAsUser: 0
    command:
    - sleep
    args:
    - 99d
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: springapp-pvc
    - name: kaniko-volume
      projected:
        sources:
        - secret:
            name: docker-secret
            items:
              - key: .dockerconfigjson
                path: config.json
  serviceAccount: springapp
  imagePullSecrets:
    - name: docker-secret
